In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import sklearn
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

2023-11-30 23:37:08.233758: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-30 23:37:08.268266: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-30 23:37:08.268772: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-30 23:37:08.898735: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
x1 = np.load('3d_rendering_x.npy')
x2 = np.load('digit_recognition_x.npy')
x3 = np.load('spam_filter_x.npy')

y1 = np.load('3d_rendering_y.npy')
y2 = np.load('digit_recognition_y.npy')
y3 = np.load('spam_filter_y.npy')

x = np.concatenate((x1,x2,x3), axis=0)
y = np.concatenate((y1,y2,y3), axis=0)

In [4]:
x.shape

(20, 64)

In [5]:
y.shape

(20,)

In [6]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(X,Y,test_size = 0.1, random_state = 0)

NameError: name 'model_selection' is not defined

In [7]:
encoder = LabelEncoder()
encoder.fit(y)
y = encoder.transform(y)
y = to_categorical(y)

In [8]:
tr_x = x
te_x = x

tr_y = y
te_y = y

In [9]:
y

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [10]:
# def baseline_model():
    # Create model here
model = Sequential()
model.add(Dense(32, input_dim = 64, activation = 'relu')) # Rectified Linear Unit Activation Function
model.add(Dense(16, activation = 'relu'))
model.add(Dense(3, activation = 'softmax')) # Softmax for multi-class classification
    # Compile model here
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

model.fit(tr_x, tr_y, epochs = 55)

scores = model.evaluate(te_x, te_y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
    # return model

Epoch 1/55


2023-11-30 23:37:25.144347: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-11-30 23:37:25.147641: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


1/1 [==============================] - 0s 415ms/step - loss: 1.1277 - accuracy: 0.1500
Epoch 2/55
1/1 [==============================] - 0s 3ms/step - loss: 1.1020 - accuracy: 0.2000
Epoch 3/55
1/1 [==============================] - 0s 4ms/step - loss: 1.0784 - accuracy: 0.2000
Epoch 4/55
1/1 [==============================] - 0s 4ms/step - loss: 1.0555 - accuracy: 0.2500
Epoch 5/55
1/1 [==============================] - 0s 3ms/step - loss: 1.0335 - accuracy: 0.4000
Epoch 6/55
1/1 [==============================] - 0s 3ms/step - loss: 1.0125 - accuracy: 0.6000
Epoch 7/55
1/1 [==============================] - 0s 3ms/step - loss: 0.9919 - accuracy: 0.6500
Epoch 8/55
1/1 [==============================] - 0s 3ms/step - loss: 0.9720 - accuracy: 0.6500
Epoch 9/55
1/1 [==============================] - 0s 3ms/step - loss: 0.9527 - accuracy: 0.6500
Epoch 10/55
1/1 [==============================] - 0s 3ms/step - loss: 0.9340 - accuracy: 0.6500
Epoch 11/55
1/1 [==============================]

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 3)                 51        
                                                                 
Total params: 2659 (10.39 KB)
Trainable params: 2659 (10.39 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.save('nnmodel.h5')

/home/aamod/.local/lib/python3.8/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [12]:
xGemm = np.load('gemm_x.npy')

In [14]:
xGemm[0].shape

(64,)

In [15]:
model.predict(xGemm)

1/1 [==============================] - 0s 47ms/step


array([[0.2451876 , 0.6835485 , 0.07126386],
       [0.19465807, 0.70958877, 0.09575318],
       [0.18232717, 0.7568289 , 0.06084402]], dtype=float32)

In [16]:
def givePragma(x , model):
    y = []
    preds = model.predict(x)
    for pred in preds:
        if (np.argmax(pred)) == 0:
            y.append("No Pragma")
        elif (np.argmax(pred)) == 1:
            y.append("Pipeline Pragma")
        elif (np.argmax(pred)) == 2:
            y.append("Unroll Pragma")
    
    return y


In [25]:
ycheck = np.load('digit_recognition_y.npy')

In [26]:
np.unique(ycheck)

array([1, 3])

In [19]:
givePragma(xGemm , model)

1/1 [==============================] - 0s 14ms/step


['Pipeline Pragma', 'Pipeline Pragma', 'Pipeline Pragma']